### ISSUE TITLE
iOS mobile app deep links not working

### ISSUE THREAD

**Issue by dpa99c** [cabify/cabify_developers#21]
I wasn't sure where to report this, so I've opened the issue here.

I have an [issue open against my Launch Navigator Cordova plugin](https://github.com/dpa99c/phonegap-launch-navigator/issues/155) to add support for launching Cabify.

While the URL scheme documented at http://developers.cabify.com/#mobile-deeplink works fine for Android, I am not able to get it working for iOS.

I am testing using the example URL from the documentation, but the Cabify iOS app fails to be launched. 
I have of course added `cabify` to the `LSApplicationQueriesSchemes` in the plist.

The code I'm testing with is:

    NSString* url = @"cabify://cabify/journey?json={\"vehicle_type\":\"c52ce29f50438491f8d6e55d5259dd40\",\"stops\":[{\"loc\":{\"latitude\":40.3979288915956,\"longitude\":-3.70257262140512 },\"name\":\"Goiko%20Grill\"},{\"loc\":{\"latitude\":40.697,\"longitude\":-3.90257262140512}}]}";
    NSLog(url);
    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:url]];
    
The log output to the Xcode console is:    

    2017-09-30 22:19:31.810099+0100 Launch Navigator Advanced Example[2392:1754560] cabify://cabify/journey?json={"vehicle_type":"c52ce29f50438491f8d6e55d5259dd40","stops":[{"loc":{"latitude":40.3979288915956,"longitude":-3.70257262140512 },"name":"Goiko%20Grill"},{"loc":{"latitude":40.697,"longitude":-3.90257262140512}}]}
        
but the iOS app fails to launch.

I would appreciate any suggestions you have to make this work.

**Comment by dpa99c** [comment]
Any updates on this?

Just retested Cabify v7.1.4 for iOS and the issue remains the same: calling the `cabify://` URL scheme does not launch the app.

**Comment by marcalrech** [comment]
You need set information to info.plist.
Try adding the 'cabify' value in LSApplicationQueriesSchemes.

**Comment by dpa99c** [comment]
@marcalrech This `LSApplicationQueriesSchemes` entry is [added automatically by my plugin](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L92) along with the schemes for the other 14 iOS navigator apps that are supported. And `canOpenURL` returns `TRUE` for `cabify://` so this indicates the URL scheme is available to call. 

So either the URL being constructed by the plugin is wrong or Cabify is not responding to the URL scheme as it should.

**Comment by marcalrech** [comment]
I use the same URL for both Android and IOS.
The method I use and works on swift 4 is below.

func openCabify(latitudeFrom: Double, longitudeFrom: Double, latitudeTo: Double, longitudeTo: Double, localNameTo: String)
{
    let cabifyUrl = "cabify://cabify/journey?json={\"vehicle_type\":\"\",\"stops\":[{\"loc\":{\"latitude\":\(latitudeFrom),\"longitude\":\(longitudeFrom)}},{\"loc\":{\"latitude\":\(latitudeTo),\"longitude\":\(longitudeTo),\"name\":\"\(localNameTo)\"}}]}".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
    if let url = URL(string: cabifyUrl)
    {
        if UIApplication.shared.canOpenURL(url)
        {
            UIApplication.shared.open(url, options: [:], completionHandler: { (result) in
                print("cabify opened::" + String(result))
            })
        }
        else
        {
            let urlAppleStore = URL(string: "http://itunes.apple.com/us/app/id476087442")!
            UIApplication.shared.open(urlAppleStore, options: [:], completionHandler: { (result) in
                print("applestore::" + String(result))
            })
        }
    }
}

**Comment by dpa99c** [comment]
I've finally got this working with Cabify v7.1.6 for iOS using the URL scheme such as:

    cabify://cabify/journey?json=%7B%22vehicle_type%22:%22%22,%22stops%22:%5B%7B%22loc%22:%7B%22longitude%22:-3.7327020168304443,%22latitude%22:40.305004119873047%7D,%22name%22:%22Getafe%22%7D,%7B%22loc%22:%7B%22longitude%22:-3.7016904354095459,%22latitude%22:40.434230804443359%7D,%22name%22:%22Madrid%22%7D%5D%7D

Things I was doing wrong:

- Percent-encoding the literal colon (`:`) character as `%3A`
- Quoting the latitude/longitude values (which is actually what valid JSON should do), for example:

    longitude%22:%22-3.7327020168304443%22,%22latitude%22:%2240.305004119873047%22

instead of 

    longitude%22:-3.7327020168304443,%22latitude%22:40.305004119873047
